In [1]:
#
import pandas as pd
pd.set_option('display.max_columns', None)

#
import numpy as np

#
import warnings

## 01. Exploración de datos.

In [12]:
df_flight_activity = pd.read_csv("../data/Customer Flight Activity.csv")

In [13]:
df_loyalty = pd.read_csv("../data/Customer Loyalty History.csv")

### Flight Activiy

In [14]:
df_flight_activity.head()

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
0,100018,2017,1,3,0,3,1521,152.0,0,0
1,100102,2017,1,10,4,14,2030,203.0,0,0
2,100140,2017,1,6,0,6,1200,120.0,0,0
3,100214,2017,1,0,0,0,0,0.0,0,0
4,100272,2017,1,0,0,0,0,0.0,0,0

In [17]:
df_flight_activity.tail()

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
405619,999902,2018,12,0,0,0,0,0.0,0,0
405620,999911,2018,12,0,0,0,0,0.0,0,0
405621,999940,2018,12,3,0,3,1233,123.0,0,0
405622,999982,2018,12,0,0,0,0,0.0,0,0
405623,999986,2018,12,0,0,0,0,0.0,0,0

*Observations on the DataFrame:*

- [ ] Assess whether "Points Redeemed" and "Dollar Cost" are useful features.

In [15]:
df_flight_activity.shape

(405624, 10)

In [ ]:
df_flight_activity.info()

<class 'pandas.DataFrame'>
RangeIndex: 405624 entries, 0 to 405623
Data columns (total 10 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Loyalty Number               405624 non-null  int64
 1   Year                         405624 non-null  int64
 2   Month                        405624 non-null  int64
 3   Flights Booked               405624 non-null  int64
 4   Flights with Companions      405624 non-null  int64
 5   Total Flights                405624 non-null  int64
 6   Distance                     405624 non-null  int64
 7   Points Accumulated           405624 non-null  float64
 8   Points Redeemed              405624 non-null  int64
 9   Dollar Cost Points Redeemed  405624 non-null  int64
dtypes: float64(1), int64(9)
memory usage: 30.9 MB

*DataFrame Info Observations:*

- No null values detected in the DF.
- Column names follow a consistent style: they include spaces and use Title Case.
- "Year" and "Month" are stored as int instead of datetime:
    - [ ] Cast to datetime.